# Generated by Django 5.2.9 on 2025-12-12 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_city',
            new_name='billing_province',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_state',
            new_name='billing_ward',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_city',
            new_name='shipping_province',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_state',
            new_name='shipping_ward',
        ),
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
