# Generated by Django 6.0 on 2025-12-10 17:42

import apps.users.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.users.validators.validate_video_thumbnail], verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.users.validators.validate_resource_file], verbose_name='resource'),
        ),
    ]
