# Generated by Django 5.2.9 on 2025-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_add_guest_email_to_coupon_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='requires_login',
            field=models.BooleanField(default=False, help_text='If True, only authenticated users can use this coupon (prevents guest abuse)'),
        ),
    ]
