# Generated by Django 6.0 on 2025-12-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Discount code used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.discount'),
        ),
    ]
