# Generated by Django 6.0 on 2025-12-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual discount amount applied (calculated value, not percentage)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original course price at time of payment', max_digits=10, null=True),
        ),
    ]
