# Generated by Django 6.0 on 2025-12-10 17:42

import apps.users.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.users.validators.validate_image_file], verbose_name='avatar'),
        ),
    ]
