# Generated by Django 5.2.9 on 2025-12-11 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('held', 'Held (Pending Release)'), ('available', 'Available for Payout'), ('paid_out', 'Paid Out'), ('refunded', 'Refunded to Customer')], default='held', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(help_text='Date when balance becomes available for payout')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_balance', to='orders.orderitem')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_entries', to='vendors.vendorpayout')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_entries', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Balance',
                'verbose_name_plural': 'Vendor Balances',
                'db_table': 'vendor_balances',
                'ordering': ['-created_at'],
            },
        ),
    ]
