# Generated by Django 6.0 on 2025-12-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('system', 'System Wide'), ('course', 'Course Specific'), ('category', 'Category Specific')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcement_views',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('enrollment', 'New Enrollment'), ('course_update', 'Course Updated'), ('new_lesson', 'New Lesson Available'), ('assignment', 'New Assignment'), ('grade', 'Assignment Graded'), ('review', 'New Review'), ('reply', 'Instructor Reply'), ('payment', 'Payment Confirmation'), ('certificate', 'Certificate Issued'), ('announcement', 'Announcement'), ('message', 'New Message'), ('reminder', 'Reminder'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enrollment', models.BooleanField(default=True)),
                ('email_course_updates', models.BooleanField(default=True)),
                ('email_new_lessons', models.BooleanField(default=True)),
                ('email_assignments', models.BooleanField(default=True)),
                ('email_reviews', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_announcements', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('push_enrollment', models.BooleanField(default=True)),
                ('push_course_updates', models.BooleanField(default=True)),
                ('push_new_lessons', models.BooleanField(default=True)),
                ('push_assignments', models.BooleanField(default=True)),
                ('push_reviews', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
